### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by nick-jonas** [evancohen/sonus-electron-boilerplate#1] opened 2017-03-02 00:12 UTC
I get this error when trying to run it, not sure how to solve it:

```Uncaught Error: Cannot find module '/Users/njonas/Downloads/sonus-electron-boilerplate-master/node_modules/snowboy/lib/node/binding/Release/electron-v1.6-darwin-x64/snowboy.node'```

**Comment by NetOpWibby** [comment] 2017-03-02 16:21
Have you tried compiling [Snowboy](https://github.com/Kitt-AI/snowboy) on your system?

**Comment by evancohen** [comment] 2017-03-02 16:50
Looks like Nick's issue was resolved by changing the Electron version https://github.com/Kitt-AI/snowboy/pull/52#issuecomment-283520629. I haven't had the chance to try to reproduce this, but the last time I tested the end-to-end install on a clean machine it worked fine.

I'm going to keep this issue open until I can verify that it's not a problem.

**Comment by NetOpWibby** [comment] 2017-03-02 17:06
Awesome!

**Comment by AlexanderKozhevin** [comment] 2017-04-04 17:30
+1

**Comment by AlexanderKozhevin** [comment] 2017-04-04 19:01
@evancohen I tried to run my example, then used this one. And still getting the same thing.
I used brew to install sox. But smth is still missing. 
You can close the issue, cause maybe it because of Sierra. 
I'll try another library.

**Comment by evancohen** [comment] 2017-04-04 19:14
Shouldn't be. I'm guessing this is because of a version mismatch between what version of electron is being downloaded and what is being used as the target in [`.npmrc`](https://github.com/evancohen/sonus-electron-boilerplate/blob/master/.npmrc)

The easiest way to fix this would be to run `npm ls electron`, update `.npmrc` to reflect the correct version, `rm -r node_modules` and then `npm install` again.

**Comment by evancohen** [comment] 2017-04-05 19:39
@AlexanderKozhevin do you mind testing that fix and seeing if it works for you?

**Closed as completed** 2017-04-06 20:50 UTC
